# CORRELATION

In [1]:
import numpy as np
x = np.arange(10, 20)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [2]:
y = np.array([2, 1, 4, 5, 8, 12, 18, 25, 96, 48])
y

array([ 2,  1,  4,  5,  8, 12, 18, 25, 96, 48])

In [3]:
print(x)
print(y)

[10 11 12 13 14 15 16 17 18 19]
[ 2  1  4  5  8 12 18 25 96 48]


In [4]:
r = np.corrcoef(x, y)
r

array([[1.        , 0.75864029],
       [0.75864029, 1.        ]])

In [5]:
print(r[0, 1])
print(r[1, 0])

0.7586402890911867
0.7586402890911869


In [7]:
import scipy.stats

In [8]:
print(x)
print(y)

[10 11 12 13 14 15 16 17 18 19]
[ 2  1  4  5  8 12 18 25 96 48]


In [9]:
scipy.stats.pearsonr(x, y)    # Pearson's r

(0.7586402890911869, 0.010964341301680832)

In [10]:
scipy.stats.kendalltau(x, y)  # Kendall's tau

KendalltauResult(correlation=0.911111111111111, pvalue=2.9761904761904762e-05)

In [11]:
scipy.stats.spearmanr(x, y).correlation   # Spearman's rho

0.9757575757575757

In [12]:
r, p = scipy.stats.pearsonr(x, y)

In [13]:
r

0.7586402890911869

In [14]:
p

0.010964341301680832

In [15]:
# pandas

In [16]:
import pandas as pd

In [17]:
x = pd.Series(range(10, 20))

In [18]:
y = pd.Series([2, 1, 4, 5, 8, 12, 18, 25, 96, 48])

In [19]:
print(x)
print(y)

0    10
1    11
2    12
3    13
4    14
5    15
6    16
7    17
8    18
9    19
dtype: int64
0     2
1     1
2     4
3     5
4     8
5    12
6    18
7    25
8    96
9    48
dtype: int64


In [20]:
x.corr(y)                     # Pearson's r

0.7586402890911867

In [21]:
y.corr(x)

0.7586402890911869

In [22]:
x.corr(y, method='spearman')  # Spearman's rho

0.9757575757575757

In [23]:
x.corr(y, method='kendall')   # Kendall's tau

0.911111111111111

In [24]:
x = np.arange(10, 20)
y = np.array([2, 1, 4, 5, 8, 12, 18, 25, 96, 48])

In [25]:
print(x)
print(y)

[10 11 12 13 14 15 16 17 18 19]
[ 2  1  4  5  8 12 18 25 96 48]


In [26]:
result = scipy.stats.linregress(x, y)

In [27]:
xy = np.array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
               [2, 1, 4, 5, 8, 12, 18, 25, 96, 48]])

In [28]:
xy

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 2,  1,  4,  5,  8, 12, 18, 25, 96, 48]])

In [30]:
scipy.stats.linregress(xy)

LinregressResult(slope=7.4363636363636365, intercept=-85.92727272727274, rvalue=0.7586402890911869, pvalue=0.010964341301680825, stderr=2.257878767543913)

In [32]:
xy.T

array([[10,  2],
       [11,  1],
       [12,  4],
       [13,  5],
       [14,  8],
       [15, 12],
       [16, 18],
       [17, 25],
       [18, 96],
       [19, 48]])

In [34]:
scipy.stats.linregress(xy.T)

LinregressResult(slope=7.4363636363636365, intercept=-85.92727272727274, rvalue=0.7586402890911869, pvalue=0.010964341301680825, stderr=2.257878767543913)

In [35]:
# Pearson Corelation

In [36]:
r,p = scipy.stats.pearsonr(x,y)

In [37]:
r

0.7586402890911869

In [38]:
np.corrcoef(x,y)

array([[1.        , 0.75864029],
       [0.75864029, 1.        ]])

In [39]:
xyz = np.array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
                [2, 1, 4, 5, 8, 12, 18, 25, 96, 48],
                [5, 3, 2, 1, 0, -2, -8, -11, -15, -16]])

In [40]:
xyz

array([[ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [  2,   1,   4,   5,   8,  12,  18,  25,  96,  48],
       [  5,   3,   2,   1,   0,  -2,  -8, -11, -15, -16]])

In [42]:
np.corrcoef(xyz)

array([[ 1.        ,  0.75864029, -0.96807242],
       [ 0.75864029,  1.        , -0.83407922],
       [-0.96807242, -0.83407922,  1.        ]])

In [44]:
xyz.T

array([[ 10,   2,   5],
       [ 11,   1,   3],
       [ 12,   4,   2],
       [ 13,   5,   1],
       [ 14,   8,   0],
       [ 15,  12,  -2],
       [ 16,  18,  -8],
       [ 17,  25, -11],
       [ 18,  96, -15],
       [ 19,  48, -16]])

In [45]:
# Pandas

In [46]:
x = pd.Series(range(10, 20))

In [47]:
y = pd.Series([2, 1, 4, 5, 8, 12, 18, 25, 96, 48])

In [48]:
z = pd.Series([5, 3, 2, 1, 0, -2, -8, -11, -15, -16])

In [49]:
xy = pd.DataFrame({'x-values': x, 'y-values': y})

In [50]:
xy

x-values  y-values
0        10         2
1        11         1
2        12         4
3        13         5
4        14         8
5        15        12
6        16        18
7        17        25
8        18        96
9        19        48

In [51]:
xyz = pd.DataFrame({'x-values': x, 'y-values': y, 'z-values': z})
xyz

x-values  y-values  z-values
0        10         2         5
1        11         1         3
2        12         4         2
3        13         5         1
4        14         8         0
5        15        12        -2
6        16        18        -8
7        17        25       -11
8        18        96       -15
9        19        48       -16

In [52]:
x.corr(y)

0.7586402890911867

In [53]:
xy.corr()

x-values  y-values
x-values   1.00000   0.75864
y-values   0.75864   1.00000

In [54]:
xyz.corr()

x-values  y-values  z-values
x-values  1.000000  0.758640 -0.968072
y-values  0.758640  1.000000 -0.834079
z-values -0.968072 -0.834079  1.000000

In [55]:
u, u_with_nan = pd.Series([1, 2, 3]), pd.Series([1, 2, np.nan, 3])
v, w = pd.Series([1, 4, 8]), pd.Series([1, 4, 154, 8])

In [56]:
u.corr(v)

0.9966158955401239

In [57]:
u_with_nan.corr(w)

0.9966158955401239