In [6]:
def my_function ():
    "This print as string"
    print ("Hello from a function")

In [7]:
my_function ()

Hello from a function


In [8]:
my_function()

Hello from a function


In [9]:
def printme (nama): # parameter # nama bakal holds value mazaya / nama saya adalah ...
    "This print as nama string into this function"
    print(nama)

In [10]:
printme("Mazaya") # argument

Mazaya


In [11]:
printme("Nama saya adalah ...")

Nama saya adalah ...


In [14]:
def printme (nama, alamat): # parameter # nama bakal holds value mazaya / nama saya adalah ...
    "This print as nama string into this function"
    print(nama)
    print(alamat)

In [15]:
printme ()

TypeError: printme() missing 2 required positional arguments: 'nama' and 'alamat'

In [17]:
printme ("mazaya", "jateng")

mazaya
jateng


In [18]:
printme (alamat="jateng",nama="mazaya")

mazaya
jateng


In [21]:
def printme (nama="Mazaya", alamat="jateng"): # parameter # nama bakal holds value mazaya / nama saya adalah ...
    "This print as nama string into this function"
    print(nama)
    print(alamat)
    return

In [22]:
printme()

Mazaya
jateng


In [23]:
printme("Inalum")

Inalum
jateng


In [24]:
printme(alamat="jakarta")

Mazaya
jakarta


In [26]:
printme("inalum", "jakarta")

inalum
jakarta


In [29]:
def printinfo(arg1,*vartuple):
    "This print a variable passed arguments"
    print("Output is: ")
    print(arg1)
    for var in vartuple:
        print (var)
    return;

In [30]:
printinfo(30)

Output is: 
30


In [31]:
printinfo(1,2,3,4,5,6,7,8,9,10)

Output is: 
1
2
3
4
5
6
7
8
9
10


In [32]:
sum = lambda arg1, arg2: arg1 + arg2;

In [33]:
sum(10,20)

30

In [35]:
print("Value of total: ", sum(20, 20))

Value of total:  40


In [44]:
def sum(arg1, arg2):
    total = arg1 + arg2
    total1 = total + 50
    return total, total1

In [45]:
sum(10,20)

(30, 80)

In [46]:
sum(10,20)

(30, 80)

In [53]:
kucing = 20

def jumlahhewan ():
    kelinci = 30
    hewan = kucing + kelinci
    return hewan

In [54]:
jumlahhewan()

50

In [60]:
kucing = 20

def jumlahhewan ():
    kelinci = 30
    hewan = kucing + kelinci
    return hewan

def tambahhewan():
    anjing = 20
    tambahan = anjing + kucing
    return tambahan

In [61]:
tambahhewan()

40

In [63]:
kucing = 20

def jumlahhewan ():
    kelinci = 30
    hewan = kucing + kelinci
    return hewan

def tambahhewan():
    anjing = 20
    tambahan = anjing + kelinci
    return tambahan

In [64]:
tambahhewan()

NameError: name 'kelinci' is not defined

In [65]:
import sys

In [66]:
sys.path

['C:\\Users\\spo',
 'C:\\Users\\spo\\Anaconda3\\python37.zip',
 'C:\\Users\\spo\\Anaconda3\\DLLs',
 'C:\\Users\\spo\\Anaconda3\\lib',
 'C:\\Users\\spo\\Anaconda3',
 '',
 'C:\\Users\\spo\\Anaconda3\\lib\\site-packages',
 'C:\\Users\\spo\\Anaconda3\\lib\\site-packages\\win32',
 'C:\\Users\\spo\\Anaconda3\\lib\\site-packages\\win32\\lib',
 'C:\\Users\\spo\\Anaconda3\\lib\\site-packages\\Pythonwin',
 'C:\\Users\\spo\\Anaconda3\\lib\\site-packages\\IPython\\extensions',
 'C:\\Users\\spo\\.ipython']

In [70]:
sys.path.append(r'/User/spo/Desktop/H8package/')

In [71]:
sys.path

['C:\\Users\\spo',
 'C:\\Users\\spo\\Anaconda3\\python37.zip',
 'C:\\Users\\spo\\Anaconda3\\DLLs',
 'C:\\Users\\spo\\Anaconda3\\lib',
 'C:\\Users\\spo\\Anaconda3',
 '',
 'C:\\Users\\spo\\Anaconda3\\lib\\site-packages',
 'C:\\Users\\spo\\Anaconda3\\lib\\site-packages\\win32',
 'C:\\Users\\spo\\Anaconda3\\lib\\site-packages\\win32\\lib',
 'C:\\Users\\spo\\Anaconda3\\lib\\site-packages\\Pythonwin',
 'C:\\Users\\spo\\Anaconda3\\lib\\site-packages\\IPython\\extensions',
 'C:\\Users\\spo\\.ipython',
 'C:/Users/spo/Desktop/H8package/',
 '/User/spo/Desktop/H8package/']

In [73]:
import mod

In [75]:
mod.s

'Hactive8 Inalum for Data Science'

In [76]:
mod.a

[100, 200, 300]

In [77]:
mod.foo('Mazaya')

Mazaya


In [78]:
from mod import s, foo

In [79]:
s

'Hactive8 Inalum for Data Science'

In [80]:
foo('Mazaya')

Mazaya


In [81]:
from mod import s as string

In [82]:
string

'Hactive8 Inalum for Data Science'

In [83]:
import mod as my_module

In [84]:
my_module.a

[100, 200, 300]

In [85]:
my_module.s

'Hactive8 Inalum for Data Science'

In [86]:
import numpy as np

In [125]:
sys.path.append(r'/User/spo/Desktop/')

In [126]:
sys.path

['C:\\Users\\spo',
 'C:\\Users\\spo\\Anaconda3\\python37.zip',
 'C:\\Users\\spo\\Anaconda3\\DLLs',
 'C:\\Users\\spo\\Anaconda3\\lib',
 'C:\\Users\\spo\\Anaconda3',
 '',
 'C:\\Users\\spo\\Anaconda3\\lib\\site-packages',
 'C:\\Users\\spo\\Anaconda3\\lib\\site-packages\\win32',
 'C:\\Users\\spo\\Anaconda3\\lib\\site-packages\\win32\\lib',
 'C:\\Users\\spo\\Anaconda3\\lib\\site-packages\\Pythonwin',
 'C:\\Users\\spo\\Anaconda3\\lib\\site-packages\\IPython\\extensions',
 'C:\\Users\\spo\\.ipython',
 'C:/Users/spo/Desktop/H8package/',
 '/User/spo/Desktop/H8package/',
 '/User/spo/Desktop/',
 '/User/spo/Desktop/',
 '/User/spo/Desktop/',
 '/User/spo/Desktop/',
 '/User/spo/Desktop/',
 '/User/spo/Desktop',
 '/User/spo/Desktop/H8package',
 '/User/spo/Desktop/',
 '/User/spo/Desktop/']

In [127]:
import H8package

ModuleNotFoundError: No module named 'H8package'

In [106]:
s

'Hactive8 Inalum for Data Science'

In [96]:
!pip --version

pip 20.0.2 from C:\Users\spo\Anaconda3\lib\site-packages\pip (python 3.7)



In [97]:
!pip install requests

In [98]:
import requests

In [99]:
sys.path.append(r'/User/spo/Desktop/')

In [101]:
import H8package.mod

ModuleNotFoundError: No module named 'H8package'

In [109]:
sys.path.append(r'/User/spo/Desktop/')

In [110]:
import H8package.mod

ModuleNotFoundError: No module named 'H8package'

In [111]:
import sys

In [112]:
sys.path

['C:\\Users\\spo',
 'C:\\Users\\spo\\Anaconda3\\python37.zip',
 'C:\\Users\\spo\\Anaconda3\\DLLs',
 'C:\\Users\\spo\\Anaconda3\\lib',
 'C:\\Users\\spo\\Anaconda3',
 '',
 'C:\\Users\\spo\\Anaconda3\\lib\\site-packages',
 'C:\\Users\\spo\\Anaconda3\\lib\\site-packages\\win32',
 'C:\\Users\\spo\\Anaconda3\\lib\\site-packages\\win32\\lib',
 'C:\\Users\\spo\\Anaconda3\\lib\\site-packages\\Pythonwin',
 'C:\\Users\\spo\\Anaconda3\\lib\\site-packages\\IPython\\extensions',
 'C:\\Users\\spo\\.ipython',
 'C:/Users/spo/Desktop/H8package/',
 '/User/spo/Desktop/H8package/',
 '/User/spo/Desktop/',
 '/User/spo/Desktop/',
 '/User/spo/Desktop/',
 '/User/spo/Desktop/']

In [118]:
sys.path.append(r'/User/spo/Desktop/H8package')

In [119]:
sys.path

['C:\\Users\\spo',
 'C:\\Users\\spo\\Anaconda3\\python37.zip',
 'C:\\Users\\spo\\Anaconda3\\DLLs',
 'C:\\Users\\spo\\Anaconda3\\lib',
 'C:\\Users\\spo\\Anaconda3',
 '',
 'C:\\Users\\spo\\Anaconda3\\lib\\site-packages',
 'C:\\Users\\spo\\Anaconda3\\lib\\site-packages\\win32',
 'C:\\Users\\spo\\Anaconda3\\lib\\site-packages\\win32\\lib',
 'C:\\Users\\spo\\Anaconda3\\lib\\site-packages\\Pythonwin',
 'C:\\Users\\spo\\Anaconda3\\lib\\site-packages\\IPython\\extensions',
 'C:\\Users\\spo\\.ipython',
 'C:/Users/spo/Desktop/H8package/',
 '/User/spo/Desktop/H8package/',
 '/User/spo/Desktop/',
 '/User/spo/Desktop/',
 '/User/spo/Desktop/',
 '/User/spo/Desktop/',
 '/User/spo/Desktop/',
 '/User/spo/Desktop',
 '/User/spo/Desktop/H8package']

In [120]:
import mod

In [121]:
mod.s

'Hactive8 Inalum for Data Science'

In [128]:
mod.a

[100, 200, 300]

In [129]:
import numpy as np

In [130]:
## creating array

a = np.array([1, 2, 3])

In [131]:
a

array([1, 2, 3])

In [132]:
b = [1,2,3]

In [133]:
b

[1, 2, 3]

In [134]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [135]:
c = np.zeros(5)

In [137]:
print(c)

[0. 0. 0. 0. 0.]


In [138]:
c

array([0., 0., 0., 0., 0.])

In [139]:
d = np.ones(5)

In [140]:
print(d)

[1. 1. 1. 1. 1.]


In [141]:
np.arange(4)

array([0, 1, 2, 3])

In [142]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [143]:
np.arange(0,20,2) # start, stop, step

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [144]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [145]:
print(arr)

[1 2 3 4 5 6 7 8]


In [146]:
np.append(arr, [1, 2]) # add

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2])

In [147]:
np.delete(arr, 1) #delete

array([1, 3, 4, 5, 6, 7, 8])

In [148]:
arr = np.array ([2, 1, 5, 3, 7, 4, 6, 8])

In [149]:
print(arr)

[2 1 5 3 7 4 6 8]


In [152]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [151]:
np.sort(arr) # sorting

array([1, 2, 3, 4, 5, 6, 7, 8])

In [153]:
## shape dan size

In [159]:
array_example = np.array([
    [[0,1,2,3],
     [4,5,6,7]],
    [[0,1,2,3],
     [4,5,6,7]],
    [[0,1,2,3],
     [4,5,6,7]]
])

In [160]:
print(array_example)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [161]:
array_example.ndim

3

In [162]:
array_example.size

24

In [163]:
array_example.shape

(3, 2, 4)

In [164]:
# reshape

In [166]:
a = np.arange(6)

print(a)

[0 1 2 3 4 5]


In [167]:
b = a.reshape(3,2)

In [168]:
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [171]:
a.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [175]:
# convert 1D to 2D

In [173]:
a

array([0, 1, 2, 3, 4, 5])

In [174]:
a.shape

(6,)

In [176]:
a2 = a[np.newaxis]
print(a2)
print(a2.shape)

[[0 1 2 3 4 5]]
(1, 6)


In [179]:
row_vector = a[np.newaxis, :]
print(row_vector)
print(row_vector.shape)

[[0 1 2 3 4 5]]
(1, 6)


In [178]:
col_vector = a[:, np.newaxis]
print(col_vector)
print(col_vector.shape)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]
(6, 1)


In [180]:
print(a)

[0 1 2 3 4 5]


In [181]:
print(a.shape)

(6,)


In [184]:
d = np.expand_dims(a, axis=1)
print (d)
print(d.shape)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]
(6, 1)


In [185]:
e = np.expand_dims(a, axis=0)
print(e)
print(e.shape)

[[0 1 2 3 4 5]]
(1, 6)


In [186]:
## indexing and slicing

In [187]:
data = np.array([1,2,3])

In [188]:
data[0]

1

In [189]:
data[1]

2

In [190]:
data[0:2]

array([1, 2])

In [191]:
data[1:]

array([2, 3])

In [192]:
data[-2]

2

In [193]:
a = np.array([[1,2,3,4], [5,6,7,8], [8,10,11,12]])

In [194]:
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 8 10 11 12]]


In [195]:
a[a<5]

array([1, 2, 3, 4])

In [196]:
a[a>=8]

array([ 8,  8, 10, 11, 12])

In [197]:
lebih_lima = (a>=5)

a[lebih_lima]

array([ 5,  6,  7,  8,  8, 10, 11, 12])

In [198]:
a[(a > 2) & (a < 11)]

array([ 3,  4,  5,  6,  7,  8,  8, 10])

In [199]:
# create array from existing data

In [200]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [201]:
arr1 = arr [3:9]

In [202]:
print(arr1)

[4 5 6 7 8 9]


In [203]:
a_1 = np.array([[1, 1],
                [2, 2]])

print(a_1)  

[[1 1]
 [2 2]]


In [206]:
a_2 = np.array([[3, 3],
                [4, 4]])

print(a_2)  

[[3 3]
 [4 4]]


In [207]:
np.vstack((a_1, a_2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [208]:
np.hstack((a_1, a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [209]:
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [210]:
np.hsplit(arr, 5)

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8]), array([ 9, 10])]

In [211]:
# view and copy

In [212]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [213]:
b = a.view()

In [214]:
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [215]:
c = a.copy()

In [216]:
print(c)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [217]:
# basic array operations

In [218]:
a_1

array([[1, 1],
       [2, 2]])

In [219]:
a_2

array([[3, 3],
       [4, 4]])

In [220]:
a_2 - a_1

array([[2, 2],
       [2, 2]])

In [221]:
a_2 * a_1

array([[3, 3],
       [8, 8]])

In [222]:
a_2 / a_1

array([[3., 3.],
       [2., 2.]])

In [223]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

In [224]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [225]:
arr.sum()

55

In [226]:
a_1

array([[1, 1],
       [2, 2]])

In [227]:
a_1.sum()

6

In [228]:
a_1.sum(axis=0)

array([3, 3])

In [229]:
a_1.sum(axis=1)

array([2, 4])

In [230]:
a_1 * 1.6

array([[1.6, 1.6],
       [3.2, 3.2]])

In [231]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [232]:
a.sum()

78

In [233]:
a.min()

1

In [235]:
a.max()

12

In [236]:
a.min(axis=0)

array([1, 2, 3, 4])

In [237]:
a.min(axis=1)

array([1, 5, 9])

In [238]:
a.max(axis=0)

array([ 9, 10, 11, 12])

In [239]:
np.array([[1,2], [3,4]])

array([[1, 2],
       [3, 4]])

In [240]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [241]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [243]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [244]:
np.random.random((3,2))

array([[0.93606929, 0.51434904],
       [0.079415  , 0.07320667],
       [0.01657968, 0.23480113]])

In [245]:
# Matrix Arithmetic

In [246]:
data = np.array([[1,2],[3,4]])
print(data)

[[1 2]
 [3 4]]


In [248]:
ones = np.ones([2,2])
print(ones)

[[1. 1.]
 [1. 1.]]


In [249]:
print(data + ones)

[[2. 3.]
 [4. 5.]]


In [250]:
ones_row = np.ones([1,2])
print(ones_row)

[[1. 1.]]


In [252]:
data + ones_row

array([[2., 3.],
       [4., 5.]])

In [254]:
a_1 = np.array([[1,2,3], [4,5,6]])
print(a_1)

a_2 = np.array([[7,8], [9,10], [11,12]])
print(a_2)

[[1 2 3]
 [4 5 6]]
[[ 7  8]
 [ 9 10]
 [11 12]]


In [255]:
print(a_1.shape)
print(a_2.shape)

(2, 3)
(3, 2)


In [256]:
np.dot(a_1, a_2)

array([[ 58,  64],
       [139, 154]])

In [257]:
data = np.array([[1,2],[3,4],[5,6]])

In [258]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [259]:
data[0,1]

2

In [260]:
data[1,1]

4

In [266]:
data[1:3]

array([[3, 4],
       [5, 6]])

In [263]:
data [0:2]

array([[1, 2],
       [3, 4]])

In [267]:
data[0:2,0]

array([1, 3])

In [269]:
data[0:2, 1]

array([2, 4])

In [270]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [271]:
data.max()

6

In [272]:
data.min()

1

In [273]:
data.sum()

21

In [274]:
data.max(axis=1)

array([2, 4, 6])

In [275]:
data.max(axis=0)

array([5, 6])

In [276]:
# transposing and reshaping

In [277]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [278]:
data.T

array([[1, 3, 5],
       [2, 4, 6]])

In [280]:
data_col = np.array([[1,2,3,4,5,6]]).T
print(data_col)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [281]:
data_col.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [282]:
data_col.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [283]:
arr = np.arange(6).reshape((2,3))

In [284]:
print(arr)

[[0 1 2]
 [3 4 5]]


In [285]:
# ND Array

In [293]:
ndarr = np.array([[[1, 2], [3, 4]],
                 [[5, 6], [7, 8]]])

In [294]:
ndarr

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [295]:
np.ones((4,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [296]:
np.zeros((4,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [298]:
np.random.random((4,3,2))

array([[[0.16634091, 0.73088997],
        [0.36907356, 0.62118347],
        [0.25197085, 0.38962038]],

       [[0.07555911, 0.53911313],
        [0.83649242, 0.53504696],
        [0.34541748, 0.07285093]],

       [[0.40982526, 0.31303649],
        [0.47363425, 0.11302915],
        [0.23293392, 0.6960397 ]],

       [[0.97588141, 0.74547583],
        [0.30099009, 0.98885913],
        [0.68401105, 0.93568653]]])

In [301]:
# flatten

In [302]:
ndarr

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [300]:
ndarr.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [303]:
a = np.random.random(5)

In [304]:
print(a)

[0.36857032 0.80042585 0.81618204 0.63108934 0.10928787]


In [305]:
a.shape # rank 1 array

(5,)

In [306]:
a.T

array([0.36857032, 0.80042585, 0.81618204, 0.63108934, 0.10928787])

In [307]:
np.dot(a, a.T)

1.8528963398802474

In [309]:
a = np.random.rand(5,1)#column vector

In [310]:
print(a)

[[0.35350913]
 [0.34659826]
 [0.49952074]
 [0.28354488]
 [0.3708435 ]]


In [311]:
a.shape

(5, 1)

In [312]:
a.T

array([[0.35350913, 0.34659826, 0.49952074, 0.28354488, 0.3708435 ]])

In [313]:
np.dot(a,a.T)

array([[0.12496871, 0.12252565, 0.17658514, 0.10023571, 0.13109656],
       [0.12252565, 0.12013035, 0.17313302, 0.09827616, 0.12853371],
       [0.17658514, 0.17313302, 0.24952097, 0.14163655, 0.18524402],
       [0.10023571, 0.09827616, 0.14163655, 0.0803977 , 0.10515078],
       [0.13109656, 0.12853371, 0.18524402, 0.10515078, 0.1375249 ]])

In [319]:
a = np.random.rand(1,5)

In [320]:
a.shape

(1, 5)

In [321]:
a.shape

(1, 5)

In [322]:
a

array([[0.42937843, 0.91912489, 0.98546024, 0.55177458, 0.66547213]])

In [323]:
import numpy as np

In [324]:
ndarr = np.array([[1,2],[3,4],[5,6],[7,8]])

In [325]:
ndarr

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [326]:
ndarr = np.array([[[1,2],[3,4],[5,6],[7,8]]])