In [1]:
import math
import statistics
import numpy as np
import scipy.stats
import pandas as pd

In [2]:
x = [8.0, 1, 2.5, 4, 28.0]
x_with_nan = [8.0, 1, 2.5, math.nan, 4, 28.0]

In [3]:
x

[8.0, 1, 2.5, 4, 28.0]

In [5]:
x_with_nan

[8.0, 1, 2.5, nan, 4, 28.0]

In [10]:
y, y_with_nan = np.array(x), np.array(x_with_nan)
z, z_with_nan = pd.Series(x), pd.Series(x_with_nan)

In [11]:
y

array([ 8. ,  1. ,  2.5,  4. , 28. ])

In [12]:
y_with_nan

array([ 8. ,  1. ,  2.5,  nan,  4. , 28. ])

In [13]:
z

0     8.0
1     1.0
2     2.5
3     4.0
4    28.0
dtype: float64

In [14]:
z_with_nan

0     8.0
1     1.0
2     2.5
3     NaN
4     4.0
5    28.0
dtype: float64

In [15]:
#mean

In [16]:
#pure Python

mean_ = sum(x) / len(x)
mean_

8.7

In [19]:
#statistic lib

mean_ = statistics.mean(x)
mean_

8.7

In [18]:
mean_ = statistics.mean(x_with_nan)
mean_

nan

In [20]:
# Numpy

mean_ = np.mean(y)
mean_

8.7

In [21]:
# Numpy 2

mean_ = y.mean()
mean_

8.7

In [22]:
# Numpy with missing value

print(np.mean(y_with_nan))
print(y_with_nan.mean())

nan
nan


In [23]:
# Numpy ignore missing value

np.nanmean(y_with_nan)

8.7

In [24]:
# pandas

mean_ = z.mean()
mean_

8.7

In [25]:
# pandas with missing value

z_with_nan.mean()

8.7

In [26]:
# median

In [32]:
# statistic lib

median_ = statistics.median(x)
median_

4

In [35]:
sorted(x)

[1, 2.5, 4, 8.0, 28.0]

In [36]:
x

[8.0, 1, 2.5, 4, 28.0]

In [37]:
statistics.median_low(x[:-1])

2.5

In [38]:
statistics.median_high(x[:-1])

4

In [39]:
sorted(x_with_nan)

[1, 2.5, 4, 8.0, nan, 28.0]

In [46]:
# statistic with missing values

statistics.median(x_with_nan)

6.0

In [42]:
# numpy

median_ = np.median(y)
median_

4.0

In [44]:
median_ = np.median(y[:-1])
median_

3.25

In [47]:
# numpy with missing values

np.median(y_with_nan)

nan

In [48]:
np.nanmedian(y_with_nan)

4.0

In [49]:
# pandas

z.median()

4.0

In [50]:
# mode

In [53]:
u = [2, 3, 2, 8, 12]

v = [12, 15, 12, 15, 21, 15, 12]

In [52]:
# statistic libs
mode_ = max((u.count(item), item) for item in set(u))[1]
mode_

2

In [54]:
mode_ = statistics.mode(u)
mode_

2

In [55]:
mode_ = scipy.stats.mode(v)
mode_

ModeResult(mode=array([12]), count=array([3]))

In [56]:
u, v = np.array(u), np.array(v)

In [59]:
# scipy

mode_ = scipy.stats.mode(u)
mode_

ModeResult(mode=array([2]), count=array([2]))

In [58]:
mode_ = scipy.stats.mode(v)
mode_

ModeResult(mode=array([12]), count=array([3]))

In [60]:
mode_.mode

array([2])

In [61]:
mode_.count

array([2])

In [62]:
u, v, w = pd.Series(u), pd.Series(v), pd.Series([2, 2, math.nan])

In [64]:
# pandas

u.mode()

0    2
dtype: int32

In [65]:
v.mode()

0    12
1    15
dtype: int32

In [66]:
w.mode()

0    2.0
dtype: float64

In [76]:
# variance

In [67]:
# statistics lib

var_ = statistics.variance(x)
var_

123.2

In [68]:
# statistics lib with missing value

statistics.variance(x_with_nan)

nan

In [72]:
# numpy

var_ = np.var(y, ddof=1)
var_

123.19999999999999

In [73]:
var_ = y.var(ddof=1)
var_

123.19999999999999

In [74]:
# numpy with missing value

np.var(y_with_nan, ddof=1)

nan

In [75]:
np.nanvar(y_with_nan, ddof=1)

123.19999999999999

In [79]:
# pandas

z.var(ddof=1)

123.19999999999999

In [80]:
z_with_nan.var(ddof=1)

123.19999999999999

In [81]:
# Standard Deviation

In [82]:
# statistic lib

std_ = statistics.stdev(x)
std_

11.099549540409287

In [83]:
# numpy

np.std(y, ddof=1)

11.099549540409285

In [84]:
np.std(y_with_nan, ddof=1)

nan

In [85]:
# pandas

z.std(ddof=1)

11.099549540409285

In [86]:
z_with_nan.std(ddof=1)

11.099549540409285

In [87]:
# Skewness

In [88]:
#Scipy

scipy.stats.skew(y, bias=False)

1.9470432273905927

In [89]:
scipy.stats.skew(y_with_nan)

nan

In [90]:
# pandas

z.skew()

1.9470432273905924

In [91]:
z_with_nan.skew()

1.9470432273905924

In [92]:
# percentile

In [93]:
np.percentile(y, 5) #5%

1.3

In [94]:
np.percentile(y, 95) #95%

23.999999999999996

In [95]:
np.percentile(y, [25, 50, 75])

array([2.5, 4. , 8. ])

In [97]:
np.median(y)

4.0

In [98]:
# numpy with missing value

np.percentile(y_with_nan, 5) #5%

nan

In [99]:
np.nanpercentile(y_with_nan, 5) #5%

1.3

In [101]:
#quantile

In [102]:
# numpy

np.quantile(y, 0.05)

1.3

In [103]:
np.quantile(y, 0.95)

23.999999999999996

In [105]:
np.nanquantile(y_with_nan, [0.25, 0.5, 0.75])

array([2.5, 4. , 8. ])

In [107]:
# Pandas

z.quantile(0.05)

1.3

In [108]:
z.quantile(0.95)

23.999999999999996

In [109]:
#Range

In [110]:
#numpy

np.ptp(y)

27.0

In [111]:
np.ptp(z)

27.0

In [112]:
np.ptp(y_with_nan)

nan

In [113]:
np.ptp(z_with_nan)

nan

In [114]:
y.max() - y.min()

27.0

In [115]:
z.max() - z.min()

27.0

In [116]:
y_with_nan.max() - y_with_nan.min()

nan

In [117]:
# IQR

In [122]:
quartile_ = np.quantile(y, [0.25, 0.75])

In [123]:
quartile_

array([2.5, 8. ])

In [124]:
# Summary of descriptive stat

In [125]:
y

array([ 8. ,  1. ,  2.5,  4. , 28. ])

In [126]:
# scipy

result = scipy.stats.describe(y, ddof=1, bias=False)

In [127]:
result

DescribeResult(nobs=5, minmax=(1.0, 28.0), mean=8.7, variance=123.19999999999999, skewness=1.9470432273905927, kurtosis=3.878019618875446)

In [128]:
result.nobs

5

In [129]:
result.minmax

(1.0, 28.0)

In [130]:
result.minmax[0]

1.0

In [131]:
result.minmax[1]

28.0

In [133]:
result.variance

123.19999999999999

In [134]:
result.skewness

1.9470432273905927

In [135]:
result.mean

8.7